name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master', dependendo do seu branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js (opcional, se usar ferramentas como npm)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # pasta que será publicada